### ISSUE TITLE
output.mp4 is hardcoded

### ISSUE THREAD

**Issue by toughIQ** [badlogic/orfondl#1]
In the description the run command is stated as such, that the `output.mp4` file seems to be a parameter.
But this filename and filepath is hardcoded within the `index.js` file and does not change according to a set parameter.

`node index.js https://on.orf.at/video/14211223 output.mp4`

I am currently working on a PR regarding containerization and there I would change the output filename by default to the video ID.

Thanks

**Comment by badlogic** [comment]
Whoopsies. Happy to merge PRs. Not sure installing Docker to install Node
and ffmpeg is simpler though :p

**Comment by toughIQ** [comment]
It depends. If you are not a Node.js DEV than installing it might be somewhat troublesome. 
If you are a container person anyway, than this might help.
Just an idea.

**Comment by toughIQ** [comment]
If you dont want to hassle with containerization than I am happy to host just the image creation part on my repo, using your code and of course giving credits to your project.

**Comment by badlogic** [comment]
No,no, the PR is absolutely fine! Just merged it.
